name: Automated PRs

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  automate:
    runs-on: ubuntu-latest  # Define the operating system for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js version 18 (change as needed)

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Execute Node.js script
        run: node automatePRs.js  # Run your Node.js script here
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}  # Pass GitHub token for authentication
